apiVersion: v1
kind: Service
metadata:
  name: break-reminder-service
spec:
  type: NodePort
  selector:
    app: break-reminder
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30080
